### ISSUE TITLE
There shouldn't be pre-defined parameters.

### ISSUE THREAD

**Issue by aligoren** [harundemr/hd-js-confirm-alert#1]
There shouldn't be pre-defined parameters. For example, sweetalert requires at least one parameter to run.

https://github.com/harundemr/hd-js-confirm-alert/blob/866b89354976553ff4b1ce4e02df7d87b1383adf/js/hd-script.js#L12-L13

**Comment by harundemr** [comment]
Thats right for alert boxes. The predefined parameter is required for the confirmation boxes.
I will remove to predefined parameters for alert boxes

**Comment by aligoren** [comment]
If I have free time, I can help you. Thanks :)
